version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Altere a senha do admin aqui
    networks:
      - monitoring

volumes:
  grafana-storage:

networks:
  monitoring:
